-keep class eu.kanade.tachiyomi.extension.prochan.Prochan { *; }
-keep class eu.kanade.tachiyomi.source.** { *; }
-keep class eu.kanade.tachiyomi.source.model.** { *; }
-keep class kotlinx.serialization.** {
